# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d8e24fdeb89fa5682359f6d0cd0347d79e16593cece0c5386f2dc1b9222d04aafd84e871879584b4a69eb5b008fc0541d7836cc1b405922dd7f17737a8179b08

test:
  secret_key_base: 91577757771902787613520ce94e6d50901791eb0059a242031088f27b082fbd4bc09cfc0112713d1e1d9a82bc86d20b7f6e3ef4c4434c78734e4b082e9baa33

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
